---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    kueue.konflux-ci.dev/requests-localhost: "true"
    build.appstudio.openshift.io/repo: '{{ source_url }}/-/tree/{{ revision }}'
    build.appstudio.redhat.com/commit_sha: '{{ revision }}'
    build.appstudio.redhat.com/target_branch: '{{ target_branch }}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: pslwdrm-app-0
    appstudio.openshift.io/component: pslwdrm-app-0-comp-0
    pipelines.appstudio.openshift.io/type: build
  name: pslwdrm-app-0-comp-0-on-push
  namespace: konflux-perfscale-3-tenant
spec:
  params:
    - name: build-platforms
      value:
        - linux/amd64
        - linux/arm64
        - linux/s390x
        - linux/ppc64le
    - name: package-name
      value: libecpg
    - name: git-url
      value: "{{ source_url }}"
    - name: revision
      value: "{{ revision }}"
    - name: target-branch
      value: "{{ target_branch }}"
    - name: ociStorage
      value: "quay.io/redhat-user-workloads-stage/$(context.taskRun.namespace)/pslwdrm-app-0-comp-0:$(params.revision)"
    - name: self-ref-url
      value: "https://gitlab.cee.redhat.com/rhel-on-konflux/rpmbuild-pipeline"
    - name: self-ref-revision
      value: 501161ea2a5824f8e9e33f90e990ce7cc5595b96
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: https://gitlab.cee.redhat.com/rhel-on-konflux/rpmbuild-pipeline
      - name: revision
        value: main
      - name: pathInRepo
        value: pipeline/build-rpm-package.yaml
  taskRunTemplate:
    serviceAccountName: build-pipeline-pslwdrm-app-0-comp-0
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
